pipeline {
    agent any

    environment {
        GIT_BRANCH = 'main'
        GIT_URL    = 'https://github.com/harshaharshu463-coder/Amazon.git'
        TOMCAT_WEBAPPS = '/opt/tomcat/webapps'
    }

    stages {

        stage('Clone') {
            steps {
                git branch: "${GIT_BRANCH}", url: "${GIT_URL}"
            }
        }

        stage('Build WAR') {
            steps {
                dir('Amazon') {
                    sh 'mvn clean package'
                }
            }
        }

        stage('Deploy to Tomcat') {
            steps {
                sh '''
                echo "Deploying WAR to Tomcat..."
                cp Amazon/Amazon-Web/target/*.war ${TOMCAT_WEBAPPS}/
                '''
            }
        }
    }

    post {
        success {
            echo "Build & Deployment Successful"
        }
        failure {
            echo "Deployment Failed"
        }
    }
}
